language: bash
services: docker

env:
  - VERSION=0.8.0 VARIANT=debian
  - VERSION=0.8.0 VARIANT=alpine
  - VERSION=0.7.3 VARIANT=debian
  - VERSION=0.7.3 VARIANT=alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="infinit:$VERSION-$VARIANT"

script:
  - travis_retry docker build -t "$image" "$VARIANT"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker run --rm "$image" # Run infinit --help.
  - docker run --rm "$image" --help # Run infinit --help.
  - docker run --rm "$image" infinit --help # Run infinit --help.
  - docker run --rm "$image" user --help # Run infinit user --help.
  - docker run --rm "$image" infinit user --help # Run infinit user --help.

# vim:set et ts=2 sw=2:
